### ISSUE TITLE
Advanced  Station Search query syntax

### ISSUE THREAD

**Issue by kdadmin** [segler-alex/radiobrowser-web-angular#1]
Nice work on this project - very much so needed.
Would like to use it in my media player, but can't figure out the Advanced 
Station Search query syntax.

Your example:
  http://95.179.139.106/json/stations/search

does not explain how to use the available parameters, such as tag list, etc.

Some (many) examples would be very helpfull. I've searched various archives 
with no luck.

My get requests are made directly with curl from c++.

Also - I ended up here from links on:
  https://www.radio-browser.info/#/

Thanks,

**Comment by segler-alex** [comment]
radio-browser api does accept data in a wide variety of ways. it does support GET and POST (prefered)
post data can be JSON or formdata or x-www-form-url-encoded
i will post some basic options:

```bash
curl -X POST 'https://de1.api.radio-browser.info/json/stations/search' --form 'order="clickcount"' --form 'limit="10"' --form 'reverse="true"' --form 'name="jazz"'

curl -X POST 'https://de1.api.radio-browser.info/json/stations/search' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name" :"jazz",
    "order": "clickcount",
    "limit": 10,
    "reverse": true
}'
```

thank you for your question!
i will add this to the documentation. i hope i could help you with this.

**Comment by segler-alex** [comment]
please do not forget to follow the documentation on https://api.radio-browser.info/
