### ISSUE TITLE
"Sort by"

### ISSUE THREAD

**Issue by aha999** [segler-alex/radiobrowser-web-angular#2]
When we get our search results, for example `country = SI`, we can't sort the results.

I would like to sort by name so i can verify if some stations are already added or not, then i can add them if not.

**Comment by segler-alex** [comment]
i will add a sorting
did you know that you can search for country and for name at the same time by using the search field a second time?

**Comment by aha999** [comment]
thanks for the tip, but i would have to search for every station manually on RadioBrowser and compare it to the stations that are available in my country...
