### ISSUE TITLE
Only 10 radios in a saved .m3u

### ISSUE THREAD

**Issue by gerroon** [segler-alex/radiobrowser-web-angular#6]
Hi

I was able to save all the channels in a tag in the past. I just tried it again and all I am getting is 10 radios in an .m3u

Open https://www.radio-browser.info/#/search?page=3&tagList=jazz

Save as .m3u

Open the playlist.

**Comment by scls19fr** [comment]
Hi @gerroon ,

maybe you should right click on M3U link, copy link, paste it and modify limit parameter (and also change offset)

https://de1.api.radio-browser.info/m3u/stations/search?offset=20&limit=10&tagList=jazz&hidebroken=true&order=clickcount&reverse=true

->

https://de1.api.radio-browser.info/m3u/stations/search?limit=100&tagList=jazz&hidebroken=true&order=clickcount&reverse=true

Some limits may also be defined on server side (to avoid too much data request)

Kind regards
